version: '3.8'
services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestUsers
    networks:
      - mynetwork
networks:
  mynetwork: